// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kvk.Gym;

#nullable disable

namespace kvk.Gym.Migrations
{
    [DbContext(typeof(GymDbContext))]
    [Migration("20260526171520_Update_TImeStam[4")]
    partial class Update_TImeStam4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gym")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kvk.Gym.Domain.DayEndRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualCashCount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CashFromPrevDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Discrepancy")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ExpectedCashTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HoldForNextDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("NextWorkingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentDate")
                        .HasDatabaseName("IX_DayEnd_CurrentDate");

                    b.ToTable("DayEnds", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.DayPassMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembershipPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<string>("TemporaryMembershipNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("TemporaryMembershipNumber")
                        .HasDatabaseName("IX_DayPass_TempMembershipNumber");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_DayPassMember_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_DayPassMember_TenantId_CreatedAt");

                    b.ToTable("DayPassMembers", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.MemberAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FingerprintIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawMetadata")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_MemberAttendance_MembershipId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_MemberAttendance_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_MemberAttendance_TenantId_CreatedAt");

                    b.ToTable("MemberAttendances", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.MemberPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MemberShipEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MemberShipRenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MemberShipStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_MemberPayment_MembershipId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_MemberPayment_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_MemberPayment_TenantId_CreatedAt");

                    b.ToTable("MemberPayments", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceFingerprintId1")
                        .HasColumnType("text");

                    b.Property<string>("DeviceFingerprintId2")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MemberType")
                        .HasColumnType("integer");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MembershipPlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Otp")
                        .HasMaxLength(4)
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceFingerprintId1")
                        .HasDatabaseName("IX_Membership_DeviceFingerprint1");

                    b.HasIndex("DeviceFingerprintId2")
                        .HasDatabaseName("IX_Membership_DeviceFingerprint2");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .HasDatabaseName("IX_Membership_IdentityUserId");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Membership_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_Membership_TenantId_CreatedAt");

                    b.ToTable("Memberships", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.MembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<int>("IsActive")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_MembershipPlan_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_MembershipPlan_TenantId_CreatedAt");

                    b.ToTable("MembershipPlans", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MemberPaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MemberShipEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MemberShipRenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MemberShipStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembershipNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("MembershipPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembershipPlanTitle")
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("IX_PaymentRecord_MembershipId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PaymentRecord_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_PaymentRecord_TenantId_CreatedAt");

                    b.ToTable("PaymentRecords", "gym");
                });

            modelBuilder.Entity("kvk.Gym.Domain.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("7b06f7f7-4a17-45b2-9b7c-2f6f0b49b2e2"));

                    b.Property<DateTime>("CurrentDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDayEndCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDayEndCheckedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NextWorkingDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PreviousDayEnd")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", "gym", t =>
                        {
                            t.HasCheckConstraint("CK_SystemSetting_Singleton", "\"Id\" = '7b06f7f7-4a17-45b2-9b7c-2f6f0b49b2e2'");
                        });
                });

            modelBuilder.Entity("kvk.Gym.Domain.DayPassMember", b =>
                {
                    b.HasOne("kvk.Gym.Domain.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("kvk.Gym.Domain.MemberAttendance", b =>
                {
                    b.HasOne("kvk.Gym.Domain.Membership", "Membership")
                        .WithMany("MemberAttendances")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("kvk.Gym.Domain.MemberPayment", b =>
                {
                    b.HasOne("kvk.Gym.Domain.Membership", "Membership")
                        .WithMany("MemberPayments")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("kvk.Gym.Domain.Membership", b =>
                {
                    b.HasOne("kvk.Gym.Domain.MembershipPlan", "MembershipPlan")
                        .WithMany()
                        .HasForeignKey("MembershipPlanId");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("kvk.Gym.Domain.PaymentRecord", b =>
                {
                    b.HasOne("kvk.Gym.Domain.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("kvk.Gym.Domain.Membership", b =>
                {
                    b.Navigation("MemberAttendances");

                    b.Navigation("MemberPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
