// <auto-generated />

#nullable disable

using Kvk.Cafe;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace kvk.Saloon.Migrations
{
    [DbContext(typeof(SaloonDbContext))]
    [Migration("20260905181950_Add_Saloon")]
    partial class Add_Saloon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("saloon")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kvk.Cafe.Domain.SaloonDayEnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualCashCount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CashFromPrevDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Discrepancy")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ExpectedCashTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HoldForNextDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("NextWorkingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaloonDayEnds", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.Saloon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Saloon_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_Saloon_TenantId_CreatedAt");

                    b.ToTable("Saloons", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("MemberId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("SaloonId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SaloonId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonBooking_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonBooking_TenantId_CreatedAt");

                    b.ToTable("SaloonBookings", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonBookingService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SaloonBookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaloonServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaloonStaffId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaloonBookingId");

                    b.HasIndex("SaloonServiceId");

                    b.HasIndex("SaloonStaffId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonBookingService_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonBookingService_TenantId_CreatedAt");

                    b.ToTable("SaloonBookingServices", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BufferMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SaloonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaloonId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonService_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonService_TenantId_CreatedAt");

                    b.ToTable("SaloonServices", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonSlotConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxBookingsPerSlot")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaloonId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaloonId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonSlotConfiguration_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonSlotConfiguration_TenantId_CreatedAt");

                    b.ToTable("SaloonSlotConfigurations", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid>("SaloonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaloonId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonStaff_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonStaff_TenantId_CreatedAt");

                    b.ToTable("SaloonStaffs", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaffSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("SaloonStaffId")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonStaffSchedule_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonStaffSchedule_TenantId_CreatedAt");

                    b.ToTable("SaloonStaffSchedules", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaffService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaloonServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaloonStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SaloonServiceId");

                    b.HasIndex("SaloonStaffId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SaloonStaffService_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_SaloonStaffService_TenantId_CreatedAt");

                    b.ToTable("SaloonStaffServices", "saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonBooking", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.Saloon", "Saloon")
                        .WithMany("Bookings")
                        .HasForeignKey("SaloonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonBookingService", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.SaloonBooking", "Booking")
                        .WithMany("Services")
                        .HasForeignKey("SaloonBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kvk.Saloon.Domain.SaloonService", "Service")
                        .WithMany("BookingServices")
                        .HasForeignKey("SaloonServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kvk.Saloon.Domain.SaloonStaff", "Staff")
                        .WithMany("BookingServices")
                        .HasForeignKey("SaloonStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonService", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.Saloon", "Saloon")
                        .WithMany("Services")
                        .HasForeignKey("SaloonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonSlotConfiguration", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.Saloon", "Saloon")
                        .WithMany("SlotConfigurations")
                        .HasForeignKey("SaloonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaff", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.Saloon", "Saloon")
                        .WithMany("Staff")
                        .HasForeignKey("SaloonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saloon");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaffSchedule", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.SaloonStaff", "Staff")
                        .WithMany("Schedules")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaffService", b =>
                {
                    b.HasOne("kvk.Saloon.Domain.SaloonService", "Service")
                        .WithMany("StaffServices")
                        .HasForeignKey("SaloonServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kvk.Saloon.Domain.SaloonStaff", "Staff")
                        .WithMany("StaffServices")
                        .HasForeignKey("SaloonStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.Saloon", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Services");

                    b.Navigation("SlotConfigurations");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonBooking", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonService", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("StaffServices");
                });

            modelBuilder.Entity("kvk.Saloon.Domain.SaloonStaff", b =>
                {
                    b.Navigation("BookingServices");

                    b.Navigation("Schedules");

                    b.Navigation("StaffServices");
                });
#pragma warning restore 612, 618
        }
    }
}
