// <auto-generated />

#nullable disable

using Kvk.Cafe;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace kvk.Saloon.Migrations
{
    [DbContext(typeof(SaloonDbContext))]
    [Migration("20260905075608_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("saloon")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kvk.Cafe.Domain.SaloonDayEnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualCashCount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CashFromPrevDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Discrepancy")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ExpectedCashTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HoldForNextDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("NextWorkingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaloonDayEnds", "saloon");
                });
#pragma warning restore 612, 618
        }
    }
}
