<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <!-- OpenAPI & Swagger -->
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
        
        <!-- JWT Authentication -->
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
        <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />

        <!-- Hangfire -->
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.12" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.20.6" />
        
        <!-- Serilog -->
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <!-- Project References -->
        <ProjectReference Include="..\kvk.Badminton\kvk.Badminton.csproj" />
        <ProjectReference Include="..\kvk.BuildingBlocks\kvk.BuildingBlocks.csproj" />
        <ProjectReference Include="..\kvk.Cafe\kvk.Cafe.csproj" />
        <ProjectReference Include="..\kvk.CarService\kvk.CarService.csproj" />
        <ProjectReference Include="..\kvk.Gaming\kvk.Gaming.csproj" />
        <ProjectReference Include="..\kvk.Gym\kvk.Gym.csproj" />
        <ProjectReference Include="..\kvk.Identity\kvk.Identity.csproj" />
        <ProjectReference Include="..\kvk.Financial\kvk.Financial.csproj" />
    </ItemGroup>

</Project>
