<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <!-- OpenAPI & Swagger -->
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1"/>
        <PackageReference Include="Scalar.AspNetCore" Version="1.2.54"/>
        
        <!-- JWT Authentication -->
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Project References -->
        <ProjectReference Include="..\kvk.BuildingBlocks\kvk.BuildingBlocks.csproj" />
        <ProjectReference Include="..\kvk.Gym\kvk.Gym.csproj" />
        <ProjectReference Include="..\kvk.Identity\kvk.Identity.csproj" />
        <ProjectReference Include="..\kvk.Financial\kvk.Financial.csproj" />
    </ItemGroup>

</Project>
