// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kvk.Gaming;

#nullable disable

namespace kvk.Gaming.Migrations
{
    [DbContext(typeof(GamingDbContext))]
    [Migration("20260701190652_Update_DayEnd")]
    partial class Update_DayEnd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("kvk.Gaming.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Game_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_Game_TenantId_CreatedAt");

                    b.ToTable("Games", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GamingCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingStationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingNumber")
                        .IsUnique();

                    b.HasIndex("GamingCategoryId");

                    b.HasIndex("GamingSlotId");

                    b.HasIndex("GamingStationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GamingBooking_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_GamingBooking_TenantId_CreatedAt");

                    b.ToTable("GamingBookings", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingBookingHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GamingCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingStationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GamingCategoryId");

                    b.HasIndex("GamingSlotId");

                    b.HasIndex("GamingStationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GamingBookingHold_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_GamingBookingHold_TenantId_CreatedAt");

                    b.ToTable("GamingBookingHolds", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GamingCategory_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_GamingCategory_TenantId_CreatedAt");

                    b.ToTable("GamingCategories", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingDayEnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualCashCount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CashFromPrevDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Discrepancy")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ExpectedCashTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("HoldForNextDay")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("NextWorkingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GamingDayEnds", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("GamingCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingSlotConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingStationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GamingCategoryId");

                    b.HasIndex("GamingSlotConfigurationId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GamingSlot_TenantId");

                    b.HasIndex("GamingStationId", "StartTime")
                        .IsUnique();

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_GamingSlot_TenantId_CreatedAt");

                    b.ToTable("GamingSlots", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingSlotConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("GamingCategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("IsActive")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("SlotGapMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GamingCategoryId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GamingSlotConfiguration_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_GamingSlotConfiguration_TenantId_CreatedAt");

                    b.ToTable("GamingSlotConfigurations", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamingCategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GamingCategoryId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_GamingStation_TenantId");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_GamingStation_TenantId_CreatedAt");

                    b.ToTable("GamingStations", "game");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingBooking", b =>
                {
                    b.HasOne("kvk.Gaming.Domain.GamingCategory", "GamingCategory")
                        .WithMany()
                        .HasForeignKey("GamingCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kvk.Gaming.Domain.GamingSlot", "GamingSlot")
                        .WithMany()
                        .HasForeignKey("GamingSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kvk.Gaming.Domain.GamingStation", "GamingStation")
                        .WithMany()
                        .HasForeignKey("GamingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GamingCategory");

                    b.Navigation("GamingSlot");

                    b.Navigation("GamingStation");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingBookingHold", b =>
                {
                    b.HasOne("kvk.Gaming.Domain.GamingCategory", null)
                        .WithMany()
                        .HasForeignKey("GamingCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kvk.Gaming.Domain.GamingSlot", null)
                        .WithMany()
                        .HasForeignKey("GamingSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("kvk.Gaming.Domain.GamingStation", null)
                        .WithMany()
                        .HasForeignKey("GamingStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingSlot", b =>
                {
                    b.HasOne("kvk.Gaming.Domain.GamingCategory", "GamingCategory")
                        .WithMany()
                        .HasForeignKey("GamingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kvk.Gaming.Domain.GamingSlotConfiguration", "GamingSlotConfiguration")
                        .WithMany()
                        .HasForeignKey("GamingSlotConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kvk.Gaming.Domain.GamingStation", "GamingStation")
                        .WithMany()
                        .HasForeignKey("GamingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamingCategory");

                    b.Navigation("GamingSlotConfiguration");

                    b.Navigation("GamingStation");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingSlotConfiguration", b =>
                {
                    b.HasOne("kvk.Gaming.Domain.GamingCategory", "GamingCategory")
                        .WithMany()
                        .HasForeignKey("GamingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamingCategory");
                });

            modelBuilder.Entity("kvk.Gaming.Domain.GamingStation", b =>
                {
                    b.HasOne("kvk.Gaming.Domain.GamingCategory", "GamingCategory")
                        .WithMany()
                        .HasForeignKey("GamingCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamingCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
